# Generated by Django 4.1.1 on 2022-09-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project', models.CharField(choices=[('LB_PROJ_GB', 'LB_PROJ_GB'), ('BT_PROJ_AU', 'LB_PROJ_GB'), ('LB_PROJ_IT', 'LB_PROJ_GB')], max_length=100)),
                ('severity', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=100)),
                ('customer_segment', models.CharField(choices=[('enterprise', 'enterprise'), ('private', 'private')], max_length=100)),
                ('crime_type', models.CharField(choices=[('terrorism', 'terrorism'), ('money laundering', 'money laundering'), ('drug trafficking', 'drug trafficking'), ('cybercrime', 'cybercrime'), ('intelectual property crime', 'intelectual property crime'), ('corruption', 'corruption')], max_length=100)),
                ('priority', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
