# Generated by Django 4.1.1 on 2022-09-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='group_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
